kanjitalk755/macemu

SheepShaver/src/MacOSX/Info.plist.in
- Add `NSHighResolutionCapable` to SheepShaver plist template.
- Tested a build on MacOS 10.14.2, preference panes now render in high resolution mode:
- Would probably work for Basilisk, but I couldn't get a build on master in order to test
=> Add high resolution flag to SheepShaver plist template

BasiliskII/src/macos_util.cpp, BasiliskII/src/prefs_items.cpp, SheepShaver/src/macos_util.cpp, SheepShaver/src/prefs_items.cpp
Similar to the ‘yearofs’ setting. Both prefs items can be combined.
For instance, using _yearofs=1_ and _dayofs=-1_ when the real date is 2019-02-09 will cause a date of 2018-02-10 inside the emulated OS.
=> Add prefs item "dayofs" for finer-grained time offset

BasiliskII/src/SDL/video_sdl2.cpp
Combined with 'scale_nearest true', this offers sharp graphics on retina
displays.
=> Enable high-resolution SDL2 rendering.

BasiliskII/src/SDL/video_sdl.cpp, BasiliskII/src/SDL/video_sdl2.cpp
Instead of using a generic list and then filtering 512x384 in SheepShaver, start with the correct list right away. This avoids SS unexpectedly refusing to run at 512x384.
=> Improve video mode handling

BasiliskII/src/SDL/video_sdl2.cpp
Re #11, this is a minor adjustment to kanjitalk's mutex deadlock fix.  I think the buffer was at risk of changing during the comparison stage, which resulted in rare frame glitches.  I did more testing with a number of games and haven't found any issues, so I'm optimistic this fix will work.
=> SDL mutex deadlock and video fix, try 2

SheepShaver/src/MacOSX/SheepShaver_Xcode8.xcodeproj/project.pbxproj
They were still pointing to SDL.framework, not SDL2.
=> Fix header search paths for kpx_cpu

SheepShaver/src/Unix/dyngen_precompiled/ppc-execute-impl.cpp, SheepShaver/src/kpx_cpu/src/cpu/ppc/ppc-decode.cpp, SheepShaver/src/kpx_cpu/src/cpu/ppc/ppc-dyngen-ops.cpp, SheepShaver/src/kpx_cpu/src/cpu/ppc/ppc-instructions.hpp, SheepShaver/src/kpx_cpu/src/cpu/ppc/ppc-operations.hpp
Also renamed the frsqrt opcode to frsqrte to match the manuals (the vector
version is also an estimate)
=> Add FP frsqrte instruction emulation

BasiliskII/src/Windows/posix_emu.cpp, BasiliskII/src/Windows/user_strings_windows.cpp, BasiliskII/src/macos_util.cpp, SheepShaver/src/Windows/user_strings_windows.cpp, SheepShaver/src/macos_util.cpp
Fixes the truncated name showing up for the extfs volume in Windows.
The data returned by `RegQueryValueEx` for a string registry value becomes `wchar_t` in the `_UNICODE` case, leading to the extfs volume showing up with just the first letter of the name.
It seems this was missed in the earlier changes for Unicode in `user_strings_windows.cpp`.
This fix unmasked another problem: the logic in `posix_emu` for creating the `Icon\r` file for the extfs volume when the `Virtual Desktop` directory is created left the file with a zeroed-out mtime and ctime (incidentally from values read out of bounds); which when the Mac did `fs_get_file_info` on the `Icon\r` file this led to the time conversion doing `localtime(-1)`, which segfaults on Windows.
I've included a fix for the time issue of the …
=> mingw32: Fix truncated extfs volume name, crash due to icon date issue

BasiliskII/src/Windows/sys_windows.cpp, BasiliskII/src/cdrom.cpp
- actually use dynamically detected cdroms
- if read via `cdenable` doesn't work use the logical drive handle instead
Fixes kanjitalk755/macemu#55
=> Fix for autodetected physical cdroms in Windows

BasiliskII/src/cdrom.cpp, BasiliskII/src/include/cdrom.h, BasiliskII/src/main.cpp, SheepShaver/src/include/macos_util.h, SheepShaver/src/macos_util.cpp, SheepShaver/src/main.cpp
Fixes NewWorld booting from physical CD when another disk image is present, part of #55 
This is an ugly solution, but for lack of any idea what else might influence NewWorld boot priority, it works.
=> Implement bootdriver pref on NewWorld by reordering the drive queue

BasiliskII/src/CrossPlatform/video_vosf.h
Some fixes for video issues in full screen mode in VOSF builds
- Vertical oddly-coloured pinstripes or bands in 800x600 in millions/thousands rakslice/macemu#46
- Skew within updates in low colour modes in resolutions with unaligned widths rakslice/macemu#51
=> VOSF full screen video problem fixes

SheepShaver/src/video.cpp
=> Fix for uninitialized value causing Quicktime image rendering to sometimes fail after mode changes

BasiliskII/src/Windows/prefs_windows.cpp, SheepShaver/src/Windows/prefs_windows.cpp
Add `"sdlrender"` pref in Windows to allow users to actually override its default of `"software"`.
=> Add "sdlrender" pref in Windows

BasiliskII/src/SDL/video_sdl2.cpp
On Windows, in windowed mode, when the `"hardcursor"` pref is set to `true`, cursor image setting with `video_set_cursor` also repositions the host cursor to the position of the emulated Mac cursor. However it does this when the cursor is not being used in the emulator, effectively stealing focus, and it moves it to the wrong place, off by the offset of the window within the screen.
- Fix for moving the cursor to the wrong place (window-relative coordinates should be used with a window-relative mouse warp)
- Added checks so the cursor is not warped in windowed mode in situations where it would interfere with other host system use
- When the window is not focused
- When the window is focused but the host cursor is not in the bounds of the window
- Make the debug message when this happens …
=> Fixes for cursor warping in "hardcursor" mode on Windows

BasiliskII/src/include/prefs.h, BasiliskII/src/prefs.cpp, BasiliskII/src/prefs_items.cpp, BasiliskII/src/slirp/slirp.c, BasiliskII/src/slirp/slirp.h, BasiliskII/src/slirp/socket.c, SheepShaver/src/prefs_items.cpp
Add a feature for slirp mode to resolve DNS requests for certain domains by looking them up on the host, rather than passing them to the host's DNS server.
The domains are configured with the new pref `host_domain`, which can be used multiple times to match multiple domains.
This is mainly intended to allow use of hostnames in the guest that are resolved using means other than regular DNS (e.g. MDNS, hosts file, WINS, etc.)
For instance, adding the pref line
```
host_domain local
```
allows hosts available through the Bonjour (MDNS) `.local` domain to be resolved on the host.
By default the list of domains is empty so this feature has no effect unless the `host_domain` pref is used.
For simplicity the host resolution is using regular `gethostbyname()` resolution within the handling of the …
=> slirp: Resolve DNS requests for a configurable set of domains using the host's name resolution

BasiliskII/src/CrossPlatform/sigsegv.cpp, SheepShaver/src/CrossPlatform/sigsegv.cpp
Add x86_64's `0x67` 32-bit address size prefix to `ix86_skip_instruction()`. Fixes rakslice/macemu#64
=> X64 32-bit address instruction skip

BasiliskII/src/MacOSX/extfs_macosx.cpp
APFS requires that the resource fork to be created. The existing fix was only doing that for files opened O_WRONLY, have modified the code to also do this for O_RDWR.
Fixes a problem I was seeing where the resource fork was not being created for files copied to the shared file system when it is an APFS file system.
=> Improved fix for resource forks not being created on APFS volumes

BasiliskII/src/Windows/main_windows.cpp, SheepShaver/src/Windows/main_windows.cpp
I made a mistake with the implementation of the new reservewindowskey option. I was only filling in keysym.sym when generating the SDL key event, but Basilisk and SheepShaver also care about keysym.scancode. This caused a problem with some keycodes files not working correctly.
See discussion:
https://www.emaculation.com/forum/viewtopic.php?p=72685
=> Include scancode when reservewindowskey is enabled

BasiliskII/src/Unix/prefs_editor_gtk.cpp, SheepShaver/src/Unix/prefs_editor_gtk.cpp
There were some issues in the GTK prefs editor for Unix. The file picker for disk creation overwrote files. It relied on the dd system utility to create the disks etc. There are still some issues left, but I hope to get to them later.
=> Volume creation changes for the Unix GTK prefs editor.

SheepShaver/src/Unix/Makefile.in
Hi, it seems that you have forgotten to add bincue.o when compiling SheepShaverGUI. Compilation error occurs on undefined references on bincue files. Please fix.
=> BINCUE support for sheepshaver

BasiliskII/src/SDL/video_sdl.cpp, BasiliskII/src/SDL/video_sdl2.cpp, BasiliskII/src/Unix/configure.ac, BasiliskII/src/Unix/keycodes, BasiliskII/src/Unix/video_x.cpp, SheepShaver/src/Unix/configure.ac, SheepShaver/src/Unix/main_unix.cpp, SheepShaver/src/Unix/video_x.cpp, SheepShaver/src/emul_op.cpp
Hi again. I've made some more fixes for the hotkey commands in SDL 1.2, as well as a change to stop SheepShaver from using the SDL Wayland video driver to work around a crash on Fedora 36. Finally I made some fixes to allow the emulators to be built with X11 video instead of SDL. This works OK in Basilisk II but SheepShaver has some problems that make it unusable at the moment, so it would need further work if anyone wanted to use it. Tested on Fedora 36 and Debian 10.
=> Further fixes

BasiliskII/src/Unix/prefs_unix.cpp, BasiliskII/src/Unix/xpram_unix.cpp, SheepShaver/src/Unix/prefs_unix.cpp
Originally authored by SegHaxx.
This is a change to comply with the XDG Base Directory Specifications, which most modern Linux applications follow. This creates a new folder called `$XDG_CONFIG_DIR/BasiliskII` to store the prefs and XPRAM files. I made some additional changes so that old files created in the home folder will still be found and loaded by default; the new folder will only be used for new users.
=> Respect XDG Base Directory Specification

BasiliskII/src/slirp/tcp_subr.c
This cast (which is also being done for ident https://github.com/kanjitalk755/macemu/blob/79f2e7e8e4069bd2472aeb45b9f0725e38395d38/BasiliskII/src/slirp/tcp_subr.c#L676) appears to be necessary to get through the Windows build
=> cast address pointer passed to getsockname

BasiliskII/src/Unix/configure.ac, BasiliskII/src/Unix/main_unix.cpp, SheepShaver/src/Unix/configure.ac, SheepShaver/src/Unix/main_unix.cpp
It turns out this fix is no longer needed, as SDL now gets initialized first and calls XInitThreads before any other Xlib functions. I tested on Debian 10 to verify that the segfault reported in #24 no longer happens.
=> Remove call to XInitThreads

BasiliskII/src/Unix/prefs_editor_gtk.cpp, SheepShaver/src/Unix/prefs_editor_gtk.cpp
There's a file drag-and-drop into the volume list feature already in the Windows gtk2 UI.
This copies it to the Unix BasiliskII and SheepShaver gtk2 UIs.
=> Add volume list file drag-and-drop from Windows gtk2 UI to the Unix gtk2 UIs

BasiliskII/src/ether.cpp, SheepShaver/src/emul_op.cpp, SheepShaver/src/ether.cpp, SheepShaver/src/include/ether.h
Invalidate the cached Ethernet guest memory allocation at guest restart.
- Includes Basilisk II, SheepShaver
- Should cover all platforms in the `SIZEOF_VOID_P != 4 || REAL_ADDRESSING == 0` case where the guest memory allocation is used
Fixes #224.
=> Invalidate cached ethernet allocation when system is reset

BasiliskII/src/Unix/Makefile.in, BasiliskII/src/Windows/Makefile.in, SheepShaver/src/Unix/Makefile.in, SheepShaver/src/Windows/Makefile.in
Running the `depend`/`dep` targets generates `make` rules for dependencies for object files corresponding to the header file inclusions of the source files, using the X11/Athena `makedepend` tool.
Previously the `macemu` builds put object files at the same location as the source code files, and this is what the `depend`/`dep` targets' previous `makedepend` run was creating rules for.  To support the current project organization where all object files are put in a single flat `obj/` directory, which `makedepend` doesn't support directly, the emitted rules are instead passed through some `sed` filtering before being concatenated to the `Makefile`.
This was tested with `makedepend` 1.0.5 from Xorg 7.7 in Debian's `xutils-dev` `1:7.7+6.2` package and GNU `sed` 4.9.
=> Update depend targets for single obj build directory

BasiliskII/src/SDL/audio_sdl3.cpp
- Push a bit more audio to SDL in each callback and don't hit the audio interrupt in a loop for no reason. Fixes #228 
- When closing audio, don't de-init the whole SDL audio system, just close the main stream so that it can be reopened again. This fixes the changing the audio parameters (mono/stereo, sample rate, bit depth) in the Sound control panel in System 7 in Basilisk.
- The routine that plays the startup sound was always erroring and didn't play the sound file when it was present, because the return value of `SDL_LoadWAV` was being flipped
=> SDL 3 audio fixes

BasiliskII/src/SDL/audio_sdl3.cpp
A data type change is all that is still needed.
=> sdl3 audio: provide float volume control value for sdl3

BasiliskII/src/SDL/audio_sdl3.cpp, BasiliskII/src/bincue.cpp
This fixes the volume passing to and from bin/cue support when using SDL 3 audio.
I have left `OpenAudio_bincue` still using integer volume values 0-128 inclusive that the old SDL audio still uses.
=> SDL 3 audio, bin/cue: interim fix for CD audio volume controls

BasiliskII/src/SDL/audio_sdl3.cpp, BasiliskII/src/bincue.cpp, BasiliskII/src/include/bincue.h
Apply the increased audio pushing from #230 when only bin/cue CD audio is playing, to avoid the same kind of audio crackling due to underruns.
=> SDL 3 audio: avoid underrun when only bin/cue is playing

BasiliskII/src/bincue.cpp
Sometimes I encountered Mac software that uses CD audio (for instance Descent II for Mac) starting audio playback in the data track, usually setting the playback start position to frame 0.
As a precaution, I added a check so that we don't start audio playback in a data track.
=> bin/cue: prevent CDPlay_bincue of data track

BasiliskII/src/SDL/video_sdl2.cpp, BasiliskII/src/SDL/video_sdl3.cpp
Move the SDL drag-and-drop handling out of the SDL redraw thread into the main thread.
While dealing with the bin/cue support I took a look at its threading situation:  Most functions are called from the main thread which takes care of most possible concurrency issues between those, with the obvious exception of `MixAudio_bincue` is called from the SDL callback in an `SDLAudioP`_n_ thread.
But there is another: The disk image drag-and-drop handling was happening directly in the SDL redraw thread, and in the case of a dropped '.cue' lead to `bincue_open()`.
I haven't identified any specific crashes or misbehaviour that results from this, but presumably not holding up the redraw thread for whatever disk I/O happens at initial disk image opening time is good, and just not avoiding a special …
=> Handle SDL drag-and-drop in main thread

BasiliskII/src/SDL/audio_sdl.cpp, BasiliskII/src/bincue.cpp, BasiliskII/src/cdrom.cpp, BasiliskII/src/include/bincue.h
This cleans up the opening/closing mess in `bincue.cpp` and some other fixes around this.
- Refactored bin/cue CD player SDL streams' opening and closing out of `OpenAudio_bincue()` and closing out of `close_bincue()` to `OpenPlayerStream`/`ClosePlayerStream`.
* Added `CloseAudio_bincue` which closes CD player streams and leaves them in a state for `OpenAudio_bincue` to open the stream again without error
* Save audio settings of most recent `OpenAudio_bincue` so that any new bin/cues opened later have their streams opened right away
- When bincue is being closed remove the pointer to its now freed CDPlayer from the collection (changed it to a list), to avoid a crash
- When a bin/cue that is currently playing is closed, stop it first, to avoid a crash
- When a preconfigured `cdrom` (which …
=> bin/cue: opening/closing and fixes

BasiliskII/src/SDL/audio_sdl3.cpp
This change puts the audio interrupt SoundComponentData handling part of the stream callback in a separate thread, and connects to remaining callback with an SDL stream rather than a queue of bytes, and uses the stream for format conversion as necessary.
- Taking the audio interrupt cycle out of the main callback isolates the possibly high latency of that from SDL3 drivers that are very sensitive to the callback taking too long (e.g. pipewire).
- Handles conversion of the audio from the SoundComponentData when necessary; generates the appropriate amount of silence if the format is unknown
Background:
Ultimately the situation I experienced working on #228 where audio would just quit after a while or immediately on any audio stoppage (for instance when changing screen modes in the emulated …
=> SDL 3 audio: use a separate thread for audio interrupt with stream

BasiliskII/src/bincue.cpp
The current code expects `FILE` with `BINARY` to have little-endian CD audio data for `AUDIO` tracks.
Add support for `MOTOROLA` keyword to support big-endian audio data for `AUDIO` tracks:
```
FILE "foo.bin" MOTOROLA
TRACK 01 MODE1/2352
INDEX 01 00:00:00
TRACK 02 AUDIO
INDEX 00 38:12:26
INDEX 01 38:14:26
...
```
(See https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Most_often_used)
Motivation:
Although little-endian audio data in `.bin` files is not uncommon, there are tools such as `sox` and `cdrdao` which consider big-endian the default for CD audio files (a.k.a. `cdda`), and for instance `cdrdao` by default produces `FILE` with `BINARY` lines in the `.cue` files and then puts big-endian audio data in the `.bin` file for audio tracks (as you will see if you create a `.bin`/`.cue` …
=> bin/cue: Implement MOTOROLA keyword for big-endian audio data

BasiliskII/src/Unix/configure.ac, BasiliskII/src/timer.cpp
I see the high precision event code from SheepShaver is now there for Basilisk II, including the `sysdeps.h` test to enable it for POSIX:
https://github.com/kanjitalk755/macemu/blob/1bedfac618b0b381b305d6515467372b8522d6be/BasiliskII/src/Unix/sysdeps.h#L502
It just doesn't have the last things brought over from SheepShaver to take effect:
- autoconf check for `clock_nanosleep()`
- `signal.h` include needed for `timer.cpp` for that case (since B2 doesn't include it in `sysdeps.h` like SheepShaver)
=> B2: Enable high precision timer for POSIX

BasiliskII/src/cdrom.cpp, SheepShaver/src/rom_patches.cpp
Mac software often issues CD audio related commands without a valid drive number, even when the commands are self-evidently for a specific drive.
To deal with multiple CD-ROMs in such circumstances, in the current code there is Seth Polsey's change 35439819d35140291295312e34f9cadd4245f5bc which just tracks the last valid drive number referenced in any call handled by the CD-ROM driver for any reason, and assumes any call without a valid drive number is for that last referenced drive.
This doesn't always work very well in practice -- with multiple CDs present, software can be actively playing audio from a CD and all of a sudden there is some kind of poll of the other drive in the background now the software is seeing that drive instead.
On a real Mac such calls aren't really ambiguous …
=> Make multiple CD-ROM drives work more realistically

BasiliskII/src/SDL/video_sdl.cpp, BasiliskII/src/SDL/video_sdl2.cpp, BasiliskII/src/SDL/video_sdl3.cpp
Avoid segfault on uninitialized SDL surface in `driver_base::adapt_to_video_mode()` if SDL did not init successfully
=> Avoid segfault if SDL did not init successfully

BasiliskII/src/Unix/ether_unix.cpp
=> Do not treat it as an error when ignoring SIGPIPE if there is already a handler installed

BasiliskII/src/Windows/prefs_editor_gtk.cpp
=> Windows: when prefs window is closed, do not run the emulator

BasiliskII/src/Unix/prefs_editor_gtk.cpp, BasiliskII/src/bincue.cpp, BasiliskII/src/cdrom.cpp
Pre-c++11 initialization compatibility changes for stuff I've added recently.
The initializer lists of `opt_desc` when it has a constructor don't even compile in old clang (~ Xcode 9).
=> More pre-c++11 compatibility changes

BasiliskII/src/Unix/configure.ac, BasiliskII/src/Windows/configure.ac, SheepShaver/src/Unix/configure.ac, SheepShaver/src/Windows/configure.ac
Fix so that the autoconf modification of the SDL3 include path works on systems where the default shell is not `bash` (or other shell that has this `+=` operator)
=> Fix for SDL3 include autoconf

BasiliskII/src/Windows/posix_emu.cpp, BasiliskII/src/macos_util.cpp, SheepShaver/src/macos_util.cpp
- Fixed an issue with extfs on Windows where the file timestamps update in `utime()` resulting from `set_finfo()` wrote the access time as the creation time
- Re-implemented `MacTimeToTime()` using `mktime()` so that those timestamps updates write the correct times, considering the difference between UTC and local time
- Added a check for the Windows so that we aren't overwriting timestamps in the case of invalid `time_t` (`-1`) values
Fixes #258
=> extfs file time fixes

BasiliskII/src/Unix/main_unix.cpp, BasiliskII/src/Unix/prefs_editor_gtk.cpp, BasiliskII/src/Unix/prefs_editor_gtk3.cpp, SheepShaver/src/Unix/main_unix.cpp, SheepShaver/src/Unix/prefs_editor_gtk.cpp
Getting the following error when compiling:
```
main_unix.cpp: In function 'void display_alert(int, int, int, const char*)':
main_unix.cpp:1684:49: error: format not a string literal and no format arguments []
1684 |         gtk_message_dialog_format_secondary_text(GTK_MESSAGE_DIALOG(dialog), text);
|         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Fixed with the attached patch.
=> Fix security related compiler error.

SheepShaver/src/Windows/main_windows.cpp
In the current SheepShaver for Windows, the command-line options for prefs don't work; the `Usage` output shows the command line options but if you try to use any of them it says `Unrecognized option`.
The problem is with the reordering in `main_windows.cpp` in 33c3419b08db536efa756a2362951bc19e1e137f : the `Unrecognized option` branch of the `if` is supposed to be last so it only sees otherwise unhandled options, but you've put it above the call to `PrefsInit` which actually handles the prefs-related options.
I've rearranged this to avoid the problem. I also added removal of the already-handled options from `argc`/`argv` before the call to `PrefsInit` for consistency with the B2 version.
=> SheepShaver Windows: fix command-line args processing

BasiliskII/src/Windows/xpram_windows.cpp
Add to the Windows version of BasiliskII the same pref option to assign a path and file name to the xpram file.
=> Add xpram path/name pref for Windows

BasiliskII/src/Unix/prefs_editor_gtk3.cpp
Usage of Glib functions for string manipulation is more consistent with the rest of the file.
=> Prefer the use of Glib functions over the strcpy family.

SheepShaver/src/Unix/configure.ac
`function` is a `ksh` extension not specified by POSIX, and might not be implemented by all POSIX-compatible `/bin/sh` implementations. `dash` in particular does not, and fails to run the configure script because of that.
=> Unix/configure: use POSIX-compatible function definition syntax

BasiliskII/src/Windows/main_windows.cpp
When I fixed the Windows port to ensure ROM is always above RAM in Windows in commit 0980a87e3f, I forgot to update the corresponding code that calls vm_release(). There is no need to try to release ROMBaseHost because the vm_release() for RAMBaseHost takes care of it.
Update the vm_release code to do the exact same thing the Unix port does.
=> Fix ROM deallocation in Windows

BasiliskII/src/Unix/configure.ac, SheepShaver/src/Unix/configure.ac
Fixes regression from change set https://github.com/kanjitalk755/macemu/commit/9a7751f1a2b2db75fbebbeef850832921e7d2a7a.
Compilation and basic functionality when run using the SDL2 library tested on Raspberry Pi Zero 2W with current Raspbian OS (Full, reference 2025-05-13) based on Debian 12 (Bookworm).
Closes issue https://github.com/kanjitalk755/macemu/issues/284.
=> Fix for SDL compilation on Unix-like systems
